jobs:
  build-on-macos-latest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18.0.2+101
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      run: mkdir staging && cp target/*.dmg staging
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: Package (.dmg)
        path: staging
  build-on-ubuntu-latest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18.0.2+101
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      run: mkdir staging && cp target/*.jar target/*.exe staging
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: Package (.jar and .exe)
        path: staging
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___java-ci-with-maven.yml
